blogicum/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path(
        'category/<slug:category_slug>/',
        views.category_posts,
        name='category_posts'
    ),
]

blogicum/blogicum/urls.py
from django.urls import include, path

urlpatterns = [
    path('pages/', include('pages.urls')),
    path('', include('blog.urls'))
]

blogicum/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('about/', views.about, name='about'),
    path('rules/', views.rules, name='rules'),
]

blogicum/blog/models.py
# Import for future model definitions
# from django.db import models  # noqa: F401

# Create your models here.

blogicum/pages/models.py
# from django.db import models

# Create your models here.

blogicum/blog/views.py
from django.shortcuts import render
from django.http import Http404


posts = [
    {
        'id': 0,
        'location': 'Остров отчаянья',
        'date': '30 сентября 1659 года',
        'category': 'travel',
        'text': '''Наш корабль, застигнутый в открытом море
                страшным штормом, потерпел крушение.
                Весь экипаж, кроме меня, утонул; я же,
                несчастный Робинзон Крузо, был выброшен
                полумёртвым на берег этого проклятого острова,
                который назвал островом Отчаяния.''',
    },
    {
        'id': 1,
        'location': 'Остров отчаянья',
        'date': '1 октября 1659 года',
        'category': 'not-my-day',
        'text': '''Проснувшись поутру, я увидел, что наш корабль сняло
                с мели приливом и пригнало гораздо ближе к берегу.
                Это подало мне надежду, что, когда ветер стихнет,
                мне удастся добраться до корабля и запастись едой и
                другими необходимыми вещами. Я немного приободрился,
                хотя печаль о погибших товарищах не покидала меня.
                Мне всё думалось, что, останься мы на корабле, мы
                непременно спаслись бы. Теперь из его обломков мы могли бы
                построить баркас, на котором и выбрались бы из этого
                гиблого места.''',
    },
    {
        'id': 2,
        'location': 'Остров отчаянья',
        'date': '25 октября 1659 года',
        'category': 'not-my-day',
        'text': '''Всю ночь и весь день шёл дождь и дул сильный
                порывистый ветер. 25 октября.  Корабль за ночь разбило
                в щепки; на том месте, где он стоял, торчат какие-то
                жалкие обломки,  да и те видны только во время отлива.
                Весь этот день я хлопотал  около вещей: укрывал и
                укутывал их, чтобы не испортились от дождя.''',
    },
]


posts_dict = {post['id']: post for post in posts}


def index(request):
    return render(request, 'blog/index.html', {'posts': posts[::-1]})


def post_detail(request, post_id):
    post = posts_dict.get(post_id)
    if not post:
        raise Http404(f"Пост с post_id={post_id} не найден")
    return render(request, 'blog/detail.html', {'post': post})


def category_posts(request, category_slug):
    return render(
        request,
        'blog/category.html',
        {'category_slug': category_slug},
    )

blogicum/pages/views.py
from django.shortcuts import render


def about(request):
    return render(request, 'pages/about.html')


def rules(request):
    return render(request, 'pages/rules.html')

blogicum/templates/blog/category.html
{% load static %}
<!DOCTYPE html>
<html lang="ru"> 
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Публикации в категории {{ category_slug }}</title>
  </head>
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="{% url 'blog:index' %}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            Блогикум
          </a>        
          <ul class="nav  nav-pills">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:index' %}">
                Лента записей
              </a>
            </li>
            <li class="nav-item">              
              <a class="nav-link" href="{% url 'pages:about' %}">
                О проекте
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pages:rules' %}">
                Наши правила
              </a>
            </li>
          </ul>      
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5">
        <h1>Публикации в категории {{ category_slug }}</h1>   
      </div>
    </main>
    <footer class="border-top text-center py-3">
      <p>© Блогикум</p>    
    </footer>
  </body>
</html>

blogicum/templates/blog/detail.html
{% load static %}
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Формируется из локации и даты -->
    <title>{{ post.location }}. {{ post.date }}</title>
  </head>
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="{% url 'blog:index' %}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            Блогикум
          </a>        
          <ul class="nav  nav-pills">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:index' %}">
                Лента записей
              </a>
            </li>
            <li class="nav-item">              
              <a class="nav-link" href="{% url 'pages:about' %}">
                О проекте
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pages:rules' %}">
                Наши правила
              </a>
            </li>
          </ul>      
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5">
        <article>
          <ul>
            <li>
              Место: {{ post.location }}              
            </li>
            <li>
              Дата: {{ post.date }}
            </li>
            <li>
              Категория: <a href="{% url 'blog:category_posts' post.category %}">{{ post.category }}</a>
            </li>
          </ul>         
          <p>
            {{ post.text }}
          </p>          
        </article>                
      </div>
    </main>
    <footer class="border-top text-center py-3">
      <p>© Блогикум</p>    
    </footer>
  </body>
</html>

blogicum/templates/blog/index.html
{% load static %}
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Лента записей</title>
  </head>
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="{% url 'blog:index' %}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            Блогикум
          </a>        
          <ul class="nav  nav-pills">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'blog:index' %}">
                Лента записей
              </a>
            </li>
            <li class="nav-item">              
              <a class="nav-link" href="{% url 'pages:about' %}">
                О проекте
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pages:rules' %}">
                Наши правила
              </a>
            </li>
          </ul>      
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5">
        <h1>Лента записей</h1>                        
        <!-- Перебираем в цикле все посты -->
        {% for post in posts %}
        <hr>
        <article>
          <ul>
            <li>
              Место: {{ post.location }}              
            </li>
            <li>
              Дата: {{ post.date }}
            </li>
            <li>
              Категория: <a href="{% url 'blog:category_posts' post.category %}">{{ post.category }}</a>
            </li>
          </ul>          
          <!-- Первые 10 слов -->
          <p>
            {{ post.text|truncatewords:10 }}
          </p>
          <a href="{% url 'blog:post_detail' post.id %}">Читать полный текст</a>
        </article>
        {% endfor %}               
      </div>
    </main>
    <footer class="border-top text-center py-3">
      <p>© Блогикум</p>    
    </footer>
  </body>
</html>

blogicum/templates/pages/about.html
{% load static %}
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>О проекте</title>
  </head>
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="{% url 'blog:index' %}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            Блогикум
          </a>        
          <ul class="nav  nav-pills">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:index' %}">
                Лента записей
              </a>
            </li>
            <li class="nav-item">              
              <a class="nav-link active" href="{% url 'pages:about' %}">
                О проекте
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pages:rules' %}">
                Наши правила
              </a>
            </li>
          </ul>      
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5">                        
        <h1>О проекте</h1>
        <p>
          Блогикум — это дорогая сердцу социальная сеть, где 
          пользователи делятся своими историями, мыслями и идеями.      
        </p>
        <p>
          Истории на Блогикуме могут быть любыми короткими, длинными, 
          смешными, мудрыми и не мудрыми. Мы — это первые пользователи 
          и благодарная аудитория нашего любимого проекта.
        </p>           
      </div>
    </main>
    <footer class="border-top text-center py-3">
      <p>© Блогикум</p>    
    </footer>
  </body>
</html>

blogicum/templates/pages/rules.html
{% load static %}
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Наши правила</title>
  </head>
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="{% url 'blog:index' %}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            Блогикум
          </a>        
          <ul class="nav  nav-pills">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:index' %}">
                Лента записей
              </a>
            </li>
            <li class="nav-item">              
              <a class="nav-link" href="{% url 'pages:about' %}">
                О проекте
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'pages:rules' %}">
                Наши правила
              </a>
            </li>
          </ul>      
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5">                        
        <h1>Наши правила</h1>                             
        <p>
          <b>Cамовыражение.</b> У нас приветствуются творчество и индивидуальность. 
          Вы можете высказывать своё мнение, делиться своими историями и обсуждать 
          интересующие вас темы.
        </p>
        <p>
          <b>Уважение к другим пользователям.</b> Мы создаем дружелюбную и 
          доброжелательную атмосферу. При общении быть вежливыми, избегать 
          оскорблений и негативных комментариев.
        </p>
        <p>
          <b>Безопасность.</b> Не выкладывайте личную информацию других 
          пользователей без их согласия
        </p>
        <p>
          <b>Разнообразие.</b> У нас приветствуется разнообразие мнений и 
          точек зрения. Вы можете высказывать свою позицию и дискутировать с 
          другими пользователями, соблюдая правила вежливости и уважения.
        </p>                    
      </div>
    </main>
    <footer class="border-top text-center py-3">
      <p>© Блогикум</p>    
    </footer>
  </body>
</html>